name: Fetch News

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install requests

      - run: python script.py

      - run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add news.json
          git commit -m "Update news" || exit 0
          git push
